name: CI

on: [push, workflow_dispatch]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Python
        uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.13
          activate-environment: true
      - name: Install dependencies
        run: |
          uv sync
      - name: Check code quality
        run: |
          ruff format --check --diff
          ruff check --diff
      - uses: oven-sh/setup-bun@v2
      - name: Check typing
        run: |
          bunx pyright

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: crate-ci/typos@master

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: |
          deno fmt --check
