name: CI

on: [push, workflow_dispatch]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.13
          activate-environment: true
      - name: Install dependencies
        run: |
          uv sync
          uv pip install basedpyright ruff
      - name: Check code quality
        run: |
          ruff format --check --diff
          ruff check --diff
          basedpyright

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@master
      